### ISSUE TITLE
pointerout even if the pointer doesn't move?

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#457] opened 2022-09-21 10:44 UTC
This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1529904
Testcase https://jsbin.com/pevofukono/2/edit?html,css,js,console,output
Chrome fires pointerout even though mouse doesn't move

I think the spec is quite clear "The pointing device is moved out..."
https://w3c.github.io/pointerevents/#dfn-pointerout

**Comment by patrickhlauke** [comment] 2022-10-12 15:25
Confirmed by @flackr that Safari behaves like Firefox

**Comment by mustaqahmed** [comment] 2023-01-04 16:12
Copy-pasting my comment from the [Interop sheet](https://docs.google.com/spreadsheets/d/1K3lnen0hP0T3z7lDmUnTtTrA-qWJ5JVTvkuvhV8AQhY/edit#gid=0):

Testing challenge: very hard to write a non-flaky test.  The pointerout has to be dispatched before next pointer event dispatch.  This absence can't be asserted at pointerup because we need a follow-up event to assert the missing pointerout."

**Comment by smaug----** [comment] 2023-01-04 16:13
But we don't need a followup event, if we just check that pointerup doesn't occur before the next rAF.

This issue can be closed, but we need still a wpt.

**Comment by EdgarChen** [comment] 2023-05-25 09:44
I am going to add a test in https://bugzilla.mozilla.org/show_bug.cgi?id=1529904.

**Comment by egirard** [comment] 2024-05-13 14:55
The underlying [specification](https://w3c.github.io/pointerevents/#the-pointerout-event) states  "The user agent MUST [fire a pointer event](https://w3c.github.io/pointerevents/#dfn-fire-a-pointer-event) named [pointerout](https://w3c.github.io/pointerevents/#dfn-pointerout) when [[...]] The user agent has detected a scenario to [suppress a pointer event stream](https://w3c.github.io/pointerevents/#dfn-suppress-a-pointer-event-stream)."

I think we can agree that the test as written should satisfy the [clause](https://w3c.github.io/pointerevents/#suppressing-a-pointer-event-stream) "The user agent MUST suppress a pointer event stream when it detects that a pointer is unlikely to continue to produce events"

BUT this conflicts with the parent's [specification](https://w3c.github.io/pointerevents/#the-pointerout-event:~:text=it%20MUST%20not%20be%20fired%20until%20the%20pointing%20device%20has%20left%20the%20boundaries%20of%20the%20element%20and%20the%20boundaries%20of%20all%20of%20its%20descendants): "it MUST not be fired until the pointing device has left the boundaries of the element and the boundaries of all of its descendants"

Perhaps we should add language to clarify this?  Perhaps something like: "it MUST not be fired while the pointing device remains un-moved within the previous boundaries  of the element and the boundaries of all of its descendants.  Note that this boundary test should consider the position of elements at the time of the originating event."

**Comment by mustaqahmed** [comment] 2024-05-13 16:01
@egirard and I just discussed this and agreed the [first line](https://w3c.github.io/pointerevents/#dfn-suppress-a-pointer-event-stream:~:text=a%20pointer%20is%20unlikely%20to%20continue%20to%20produce%20events) of 4.1.3.3 is the source of the confusion here: "a pointer is unlikely to continue to produce events" currently carries the _implied_ meaning that "a pointing device is getting disconnected/isolated from the current web-content", and the spec doesn't say it explicitly.

In particular, for the popup condition there the device is not even stopping to produce events!

I will file a new issue to track this.

**Comment by mustaqahmed** [comment] 2024-09-12 14:53
I am reopening this because the conclusion here seems to contradict the related behavior in UIEvent spec!

UIEvents wants mouseover/out events w/o a movement so that hover effect is updated correctly after a layout change or scroll, see https://github.com/w3c/uievents/issues/154.  This contradicts the PointerEvent spec behavior and corresponding WPT we discussed here!

**Comment by mustaqahmed** [comment] 2024-09-12 15:11
Here are the related WPTs (with conflicting results!):
- [pointerevent_pointerout_no_pointer_movement.html](https://wpt.fyi/results/pointerevents/pointerevent_pointerout_no_pointer_movement.html?label=master&label=experimental&aligned) does not expect over/out events without a mouse movement, currently passes in Firefox ans Safari but fails in Chrome.
- [layout_change_should_fire_mouseover.html](https://wpt.fyi/results/uievents/mouse/layout_change_should_fire_mouseover.html?label=master&label=experimental&aligned) expects over/out events, currently passes in Chrome and Firefox but fails in Safari.

**Comment by smaug----** [comment] 2024-09-12 17:05
Need to think about this. Pointerevent is a pointerevent, not a mouse event, and I think so far we haven't dispatched "synthetic" pointermoves.
The tests don't conflict, they just show different behavior for mouse events and pointer events. There are quite a few cases when pointer events and mouse events work differently.


@masayuki-nakano

**Comment by mustaqahmed** [comment] 2024-09-12 18:49
https://w3c.github.io/uievents/#event-type-mouseover

> ... The tests don't conflict, they just show different behavior for mouse events and pointer events.

Thanks, that's correct: we are talking about two disjoint sets of events which have [no 1:1 correspondence](https://w3c.github.io/pointerevents/#legacy-pointer-transition)!  Is it acceptable to decouple these two sets a bit further with the restriction "synthetic mousemove events are/maybe exposed, and synthetic pointermove events are never exposed"?

**Comment by masayuki-nakano** [comment] 2024-09-13 11:40
Yeah, I don't think synthetic `pointermove` should be fired to dispatch pointer boundary events. As far as I've investigated, [Blink/WebKit may have odd behavior for the synthetic `mousemove` events for mouse boundary events if the target is temporarily removed and reconnected](https://wpt.fyi/results/uievents/mouse/mouse_boundary_events_after_reappending_last_over_target.tentative.html?run_id=5195886896611328&run_id=5194983477084160&run_id=5203867348500480&run_id=4907795589890048). The approach of Pointer Events is much clearer for better compatibility.

**Comment by mustaqahmed** [comment] 2024-11-25 22:54
I reopened this issue to discuss the Pointer/Mouse event differences.  Looks like there are other differences too.  I just create #529 for this particular discussion therefore close this issue.

**Closed as completed by mustaqahmed** 2024-11-25 22:54 UTC
Labels: v3
