### ISSUE TITLE
Should pointer capture work when element is in non-browsing-context

### ISSUE THREAD

**Issue by smaug----** [w3c/pointerevents#172] opened 2017-01-20 09:52 UTC
Per spec the following should work:

var b = document.implementation.createHTMLDocument().body;
b.setPointerCapture(id);

but why is that any different to "If the Element on which this method is invoked does not participate in its ownerDocument's tree"

**Comment by mustaqahmed** [comment] 2017-01-26 16:24
Are events even dispatched to the created document? Or orphaned nodes in general?If it is the case, I think we shouldn't allow capturing.

The following case is similar but trickier:
target.setPointerCapture(id);
document.body.removeChild(target);
document2.body.appendChild(target);
Should we release the capture when target is orphan?

I checked it in Chrome, with document2=document. The capturing is not effective---perhaps EventDispatcher is smart enough to handle this.

**Comment by mustaqahmed** [comment] 2017-01-26 16:37
The case I mentioned is already covered in Section 10.4, so removed my last post.

I don't know if the created document even receives any events. Does event dispatching mechanism already cover this case?

**Comment by smaug----** [comment] 2017-01-26 17:12
Normal dom event dispatch doesn't care about whether node is in document or is in browsing context document. It just deals with EventTarget objects and their possible ancestors.

**Comment by NavidZ** [comment] 2018-03-21 15:36
Duplicate of #219

**Closed as completed by NavidZ** 2018-03-21 15:36 UTC
Labels: question
