### ISSUE TITLE
Immediately firing coalesced events for enter/leave/over/out?

### ISSUE THREAD

**Issue by ChumpChief** [w3c/pointerevents#278] opened 2019-02-22 18:14 UTC
The [section on coalesced event firing](https://w3c.github.io/pointerevents/extension.html#timing-of-coalesced-event-firing) specifies that the coalesced events will be fired before pointerdown/up/cancel.  Seems they should also be fired before pointerenter/leave/over/out?  I think perhaps this is a natural artifact that rAF-aligned input only included down/up/cancel as immediate-dispatching events, so maybe this is really just feedback that enter/leave/over/out should have also been included in the list of events immediately dispatched with rAF-aligned input.

Unpleasant consequences of not doing this:

1. An element will not directly receive the last few events targeting it before the pointer moves out of its bounds, since those events will be coalesced and targeted to the element that it enters instead.  Reassigning those events back to their original target is additional overhead and potentially unfeasible for component authors.  This is the most painful issue I think.
2. When retrieving a list of coalesced events, the author needs to be aware that they may not all target the same element that was targeted by the coalesced event.  Authors using getCoalescedEvents must do their own filtering of the list on target if this matters to them.
3. Reconstructing the sequence of events seems burdensome to impossible.  At most only a single enter/leave event is fired after coalescing even if the boundary is crossed multiple times, and the timestamp will be at the coalesced time.  Examining target changes in the list of coalesced events could help, but if a portion of the pointer path passes through an area with no move listeners registered then the enter/leave will not be evident as no move events will be added to the list for that region.

**Comment by dtapuska** [comment] 2019-02-22 18:31
I think this is awkward because in order to determine if it is a pointerenter/leave/over/out you need to do a hit test. Even if you kept the target at the time the event first was received what element it matched in an older DOM you'd still need to hit test against the current DOM and it might not match a enter/leave/out/over because the layout was manipulated in between then. 

Associating them with a hit test removes any performance gains that rAF aligned input was designed to address, then ultimately there would be no point in doing rAF aligned input.

I believe the raw pointer movement API is ideal for these cases you've identified in 1/2.

**Comment by ChumpChief** [comment] 2019-02-22 19:27
How are the targets populated in the current list received from getCoalescedEvents?  Presumably a hit test must be done at some point in order to generate those (Deferred until the coalesced event is dispatched maybe?  Or until getCoalescedEvents is called?)

Perhaps an alternative middle-ground approach might be to not fire the events immediately (still defer until the next frame or down/up/cancel as today) but at that time reconstruct and fire the sequence at the appropriate targets, with the appropriate enter/leave events interleaved?

As currently written, I think the raw events proposal encounters the same issues since it seems to have the same rules for coalescing (just will generally tend to have less coalescing by virtue of being fired more frequently if the thread is idle)?  I'd also hate to give up frame-aligned coalescing for scenarios that are fine having the event handler called just once per frame (e.g. draw a single line connecting all coalesced points).  Even if hit testing every event is necessary I think rAF-aligned input offers benefits in cutting down on calls to move handlers in JS.

**Comment by dtapuska** [comment] 2019-02-22 19:44
I believe spec text Navid wrote is `Note that this rule doesn't apply to target and it should still be the same as the dispatched event's target.` So all coalesced events will have the same target. Each coalesced event doesn't have its target calculated it is just cloned from the parent event.

Yes you will still have the coalesced event problem even in the raw events scenario, so it further goes to the point that having the `pointerout/over/enter/leave` as discrete events doesn't fix the issue. I guess what you really want is a `really raw` event where every coalesced event ends up as a true JS event. 

Are there practical applications that this is causing issues for. A lot of the web might use event delegation and this wouldn't even apply to. Secondly we expected apps that are using coalesced events to be drawing apps and their targets would largely be a large canvas. Just trying to get my head around a concrete example.

**Comment by ChumpChief** [comment] 2019-02-23 00:36
Ah my mistake - I had forgotten that I worked around this issue by using document.elementFromPoint on each unpacked move event to get the target element.  The unpacked moves each have the same target as you say.

I'm also thinking about drawing scenarios, in particular scenarios where the canvas might be small (checkbox, signature field) and it's highly likely that a coalesced move may fall outside of the canvas but include coalesced points from inside the canvas.  After thinking some more - for this scenario I suppose pointer capture would avoid issues 1 & 2 assuming the author doesn't need the enter/leave events (or is OK using elementFromPoint if they do).  Fiddle I was playing around with here: https://jsfiddle.net/cokgdx7v/

I don't think "really raw" is what I would want in this case either.  The timing of the delivery of the coalesced event is already perfect - I don't desire to receive them any faster than once per frame because I'll only be drawing once per frame anyway.  I just want to ensure that the quantity, coordinates,  and targets of those coalesced events match what I would have received in a non-coalesced world.

**Comment by patrickhlauke** [comment] 2021-07-07 15:50
Discussed in PEWG call today. Closing this issue. Recent work on more specifically defining target etc should cover this.

**Closed as completed by patrickhlauke** 2021-07-07 15:50 UTC
Labels: v3
